const ADD_TODO = 'ADD_TODO';
const DELETE_TODO = 'DELETE_TODO';
const TOGGLE_TODO = 'TOGGLE_TODO';


const SHOW_ALL = 'SHOW_ALL';
const SHOW_DONE = 'SHOW_DONE';
const SHOW_PENDING = 'SHOW_PENDING';

const SET_VISIBLITY_FILTER = "SET_VISIBLITY_FILTER";

export {ADD_TODO, DELETE_TODO, TOGGLE_TODO, SHOW_ALL, SHOW_DONE, SHOW_PENDING, SET_VISIBLITY_FILTER};